# Generated by Django 5.0.6 on 2024-05-19 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='#LE9900', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('draft', 'Draft')], default='draft', max_length=7)),
                ('description', models.TextField()),
                ('item_total_price', models.FloatField(blank=True, default=0, null=True)),
                ('sender_username', models.CharField(max_length=50)),
                ('sender_email', models.EmailField(max_length=254, unique=True)),
                ('sender_country', models.CharField(max_length=50)),
                ('sender_city', models.CharField(max_length=50)),
                ('sender_street_address', models.CharField(max_length=50)),
                ('sender_postcode', models.CharField(max_length=30)),
                ('reciever_username', models.CharField(max_length=50)),
                ('reciever_email', models.EmailField(max_length=254)),
                ('reciever_country', models.CharField(max_length=50)),
                ('reciever_city', models.CharField(max_length=50)),
                ('reciever_street_address', models.CharField(max_length=50)),
                ('reciever_postcode', models.CharField(max_length=30)),
                ('payment_terms', models.IntegerField(choices=[(1, '1 Day'), (2, '7 Days'), (3, '14 Days'), (4, '30 Days')])),
                ('payment_start_date', models.DateField(blank=True, null=True)),
                ('payment_end_date', models.DateField(blank=True, null=True)),
                ('item_list', models.ManyToManyField(to='invoice.item')),
            ],
        ),
    ]
