# Generated by Django 5.0.6 on 2024-05-17 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('sender_username', models.CharField(max_length=50)),
                ('sender_email', models.EmailField(max_length=254, unique=True)),
                ('sender_country', models.CharField(max_length=50)),
                ('sender_city', models.CharField(max_length=50)),
                ('sender_street_address', models.CharField(max_length=50)),
                ('sender_postcode', models.CharField(max_length=30)),
                ('reciever_username', models.CharField(max_length=50)),
                ('reciever_email', models.EmailField(max_length=254, unique=True)),
                ('reciever_country', models.CharField(max_length=50)),
                ('reciever_city', models.CharField(max_length=50)),
                ('reciever_street_address', models.CharField(max_length=50)),
                ('reciever_postcode', models.CharField(max_length=30)),
                ('payment_terms', models.IntegerField(choices=[(1, '1 Day'), (2, '7 Days'), (3, '14 Days'), (4, '30 Days')])),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('item_total_price', models.FloatField(blank=True, default=0, null=True)),
                ('item_list', models.ManyToManyField(to='invoice.item')),
            ],
        ),
    ]
