# Generated by Django 5.0.6 on 2024-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
