# Generated by Django 5.0.6 on 2024-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pain', 'Paid'), ('draft', 'Draft')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
