# Generated by Django 5.0.6 on 2024-05-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_status_alter_invoice_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='reciever_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID'),
        ),
    ]
