# Generated by Django 5.0.6 on 2024-05-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_id_remove_invoice_item_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item_list',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(default='#RD4496', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_list',
            field=models.ManyToManyField(to='invoice.item'),
        ),
    ]
