# Generated by Django 5.0.6 on 2024-05-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoice_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(default='#WW1688', max_length=15),
        ),
    ]
