# Generated by Django 5.0.6 on 2024-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_invoice_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(default='new description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(default='#XM3826', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('draft', 'Draft')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
