# Generated by Django 5.0.6 on 2024-05-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_invoice_description_alter_invoice_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(default='#SU4131', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('draft', 'Draft')], default='draft', max_length=7),
        ),
    ]
