# Generated by Django 5.0.6 on 2024-05-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_invoice_serial_number_alter_invoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_due_date',
            new_name='payment_end_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(default='#VV1370', max_length=15),
        ),
    ]
