# Generated by Django 5.0.6 on 2024-05-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_rename_payment_due_date_invoice_payment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(default='#FD1220', max_length=15),
        ),
    ]
